name: multi job workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build step
        run: echo "building the app"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: test step
        run: echo "Running tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: deploy step
        run: echo "deploying"