name: Secret Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret
        env:
          MESSAGE: ${{ secrets.MESSAGE }}
        run: |
          echo "Length = ${ #MESSAGE }"
          echo "Secret loaded successfully"
