name: secrets ENV demo

on:
  workflow_dispatch:

jobs:
  env_demo:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret
        env:
          MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}

        
        run: |
          echo "Length = ${{ #MESSAGE }}"
          echo "Secret loaded successfully"

